---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hocs-case-creator
  labels:
    version: {{.VERSION}}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: hocs-case-creator
  template:
    metadata:
      labels:
        name: hocs-case-creator
        role: hocs-backend
        version: {{.VERSION}}
    spec:
      containers:
        - name: hocs-case-creator
          image: quay.io/ukhomeofficedigital/hocs-case-creator:{{.VERSION}}
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            capabilities:
              drop:
                - SETUID
                - SETGID
          envFrom:
            - configMapRef:
                name: hocs-queue-config
          env:
            - name: JAVA_OPTS
              value: >
                -Xms768m -Xmx4096m -XX:+UseG1GC 
            - name: SPRING_PROFILES_ACTIVE
              value: 'sqs, sns, s3'
            - name: CASE_CREATOR_CASE_SERVICE
              value: 'https://hocs-casework.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: CASE_CREATOR_WORKFLOW_SERVICE
              value: 'https://hocs-workflow.{{.KUBE_NAMESPACE}}.svc.cluster.local'
            - name: CASE_CREATOR_BASICAUTH
              valueFrom:
                secretKeyRef:
                  name: ui-casework-creds
                  key: plaintext
            - name: CASE_CREATOR_UKVI_COMPLAINT_USER
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-ukvi-complaint-identity
                  key: user
            - name: CASE_CREATOR_UKVI_COMPLAINT_GROUP
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-ukvi-complaint-identity
                  key: group
            - name: CASE_CREATOR_SQS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-ukvi-complaint-sqs
                  key: access_key_id
            - name: CASE_CREATOR_SQS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-ukvi-complaint-sqs
                  key: secret_access_key
            - name: CASE_CREATOR_UKVI_COMPLAINT_QUEUE_NAME
              value:
                '{{.KUBE_NAMESPACE}}-ukvi-complaint-queue'
            - name: CASE_CREATOR_UKVI_COMPLAINT_DL_QUEUE_NAME
              value:
                '{{.KUBE_NAMESPACE}}-ukvi-complaint-queue-dlq'
            - name: AUDIT_APP_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: AUDIT_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: AUDIT_SNS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-audit-sqs
                  key: access_key_id
            - name: AUDIT_SNS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-audit-sqs
                  key: secret_access_key
            - name: AUDIT_SNS_TOPIC_NAME
              value:
                '{{.KUBE_NAMESPACE}}-sns'
            - name: DOCUMENT_S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: access_key_id
            - name: DOCUMENT_S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: secret_access_key
            - name: DOCUMENT_S3_UNTRUSTED_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: bucket_name
            - name: DOCUMENT_S3_UNTRUSTED_BUCKET_KMS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{.KUBE_NAMESPACE}}-untrusted-s3
                  key: kms_key_id
          resources:
            limits:
              cpu: 2000m
              memory: 4096Mi
            requests:
              cpu: 400m
              memory: 768Mi
          readinessProbe:
            exec:
              command:
                - cat
                - /app/scripts/run.sh
            initialDelaySeconds: 30
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
                - cat
                - /app/scripts/run.sh
            initialDelaySeconds: 10
            periodSeconds: 5
